# Generated by Django 5.2.13 on 2026-05-12 04:09

from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', recipes.models.CustomUserManager()),
            ],
        ),
    ]
